N_EPOCHS: 3000
LR: 0.0001
MODEL_PATH: 'best_model_ucf10_resnet_full'

FINETUNE: False
FEAT_EXTRACTOR: 'wide_resnet50_2'
NUM_CLASSES: 10
FEATURE_DIM: 512 
NUM_ATT_HEADS: 4 
NUM_TRANSFORMER_LAYERS: 4
DROPOUT: 0.4

DATA_VIDEO_PATH: "datasets/UCF10/"
DATA_ANNOTATION_PATH: "datasets/ucf10TrainTestlist/"
DATA_NUM_SAMPLES: -1
DATA_RES: 128
VIDEO_CHUNK_LENGTH: 60
NUM_FRAMES: 20
DATA_NUM_WORKERS: 12

BATCH_SIZE: 16
