N_EPOCHS: 300
LR: 0.0001
MODEL_PATH: 'best_model_ucf50_x128_full'
FINETUNE: False

FEAT_EXTRACTOR: 'resnet18'
NUM_CLASSES: 50
FEATURE_DIM: 512 
NUM_ATT_HEADS: 4 
NUM_TRANSFORMER_LAYERS: 4

DATA_VIDEO_PATH: "datasets/UCF50/"
DATA_ANNOTATION_PATH: "datasets/ucf50TrainTestlist/"
DATA_NUM_SAMPLES: -1 #150000
DATA_RES: 128
VIDEO_CHUNK_LENGTH: 60
NUM_FRAMES: 20
DATA_NUM_WORKERS: 12

BATCH_SIZE: 32
