N_EPOCHS: 3000
LR: 0.0001
MODEL_PATH: 'best_model_ucf50_baseline_full'
FINETUNE: False

FEAT_EXTRACTOR: 'linear'
NUM_CLASSES: 50
FEATURE_DIM: 128 
NUM_ATT_HEADS: 2
NUM_TRANSFORMER_LAYERS: 2
DROPOUT: 0.5

DATA_VIDEO_PATH: "datasets/UCF50/"
DATA_ANNOTATION_PATH: "datasets/ucf50TrainTestlist/"
DATA_NUM_SAMPLES: -1
DATA_RES: 128
VIDEO_CHUNK_LENGTH: 60
NUM_FRAMES: 15
DATA_NUM_WORKERS: 12

BATCH_SIZE: 64
