N_EPOCHS: 2
LR: 0.01
MODEL_PATH: 'best_model_ucf50_x128_sub_30'
FINETUNE: False

FEAT_EXTRACTOR: 'efficientnet_v2_s'
NUM_CLASSES: 50
FEATURE_DIM: 256 
NUM_ATT_HEADS: 2 
NUM_TRANSFORMER_LAYERS: 2

DATA_VIDEO_PATH: "datasets/UCF50/"
DATA_ANNOTATION_PATH: "datasets/ucf50TrainTestlist/"
DATA_NUM_SAMPLES: 30000
DATA_RES: 128
VIDEO_CHUNK_LENGTH: 30
NUM_FRAMES: 15

BATCH_SIZE: 2
