N_EPOCHS: 3000
LR: 0.00003
MODEL_PATH: 'best_model_ucf50_wide_resnet50_2_att8'
FINETUNE: False

FEAT_EXTRACTOR: 'wide_resnet50_2'
NUM_CLASSES: 50
FEATURE_DIM: 128 
NUM_ATT_HEADS: 8
NUM_TRANSFORMER_LAYERS: 8
DROPOUT: 0.6

DATA_VIDEO_PATH: "datasets/UCF50/"
DATA_ANNOTATION_PATH: "datasets/ucf50TrainTestlist/"
DATA_NUM_SAMPLES: -1
DATA_RES: 128
VIDEO_CHUNK_LENGTH: 80
NUM_FRAMES: 20
DATA_NUM_WORKERS: 12

BATCH_SIZE: 8